<?php

namespace Omnipay\Gopay;

use Omnipay\Common\AbstractGateway;

class Gateway extends AbstractGateway {

    public function getName()
    {
        return 'GoPay';
    }

    public function getShortName()
    {
        return 'GoPay';
    }

    public function getDefaultParameters()
    {
        return parent::getDefaultParameters(); // TODO: Change the autogenerated stub
    }

    public function getParameters()
    {
        return parent::getParameters(); // TODO: Change the autogenerated stub
    }

    protected function getParameter($key)
    {
        return parent::getParameter($key); // TODO: Change the autogenerated stub
    }

    protected function setParameter($key, $value)
    {
        return parent::setParameter($key, $value); // TODO: Change the autogenerated stub
    }

    public function getTestMode()
    {
        return parent::getTestMode(); // TODO: Change the autogenerated stub
    }

    public function setTestMode($value)
    {
        return parent::setTestMode($value); // TODO: Change the autogenerated stub
    }

    public function getCurrency()
    {
        return parent::getCurrency(); // TODO: Change the autogenerated stub
    }

    public function setCurrency($value)
    {
        return parent::setCurrency($value); // TODO: Change the autogenerated stub
    }

    public function supportsAuthorize()
    {
        return parent::supportsAuthorize(); // TODO: Change the autogenerated stub
    }

    public function supportsCompleteAuthorize()
    {
        return parent::supportsCompleteAuthorize(); // TODO: Change the autogenerated stub
    }

    public function supportsCapture()
    {
        return parent::supportsCapture(); // TODO: Change the autogenerated stub
    }

    public function supportsPurchase()
    {
        return parent::supportsPurchase(); // TODO: Change the autogenerated stub
    }

    public function supportsCompletePurchase()
    {
        return parent::supportsCompletePurchase(); // TODO: Change the autogenerated stub
    }

    public function supportsRefund()
    {
        return parent::supportsRefund(); // TODO: Change the autogenerated stub
    }

    public function supportsVoid()
    {
        return parent::supportsVoid(); // TODO: Change the autogenerated stub
    }

    public function supportsCreateCard()
    {
        return parent::supportsCreateCard(); // TODO: Change the autogenerated stub
    }

    public function supportsDeleteCard()
    {
        return parent::supportsDeleteCard(); // TODO: Change the autogenerated stub
    }

    public function supportsUpdateCard()
    {
        return parent::supportsUpdateCard(); // TODO: Change the autogenerated stub
    }

    protected function createRequest($class, array $parameters)
    {
        return parent::createRequest($class, $parameters); // TODO: Change the autogenerated stub
    }

    protected function getDefaultHttpClient()
    {
        return parent::getDefaultHttpClient(); // TODO: Change the autogenerated stub
    }

    protected function getDefaultHttpRequest()
    {
        return parent::getDefaultHttpRequest(); // TODO: Change the autogenerated stub
    }
}
